movieproject/movieapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name='movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),  # Added 'name' parameter
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<style>
  body {
    background-color: #1c1c1c;
    color: #fff;
    margin: 0;
  }

  h2 {
    text-align: center;
    margin-top: 50px;
    margin-bottom: 20px;
    font-weight: bold;
    font-size: 1.8rem;
    font-family: 'Verdana', sans-serif; /* Change font family for the heading */
  }

  form {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    background-color: #333;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  }

  input[type="text"],
  input[type="file"] {
    width: 100%;
    margin-bottom: 10px;
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #444;
    border-radius: 5px;
  }

  input[type="submit"] {
    background-color: #ffc107;
    border: none;
    color: #1c1c1c;
    padding: 10px 15px;
    border-radius: 5px;
    cursor: pointer;
    font-size: 1rem;
  }

  input[type="submit"]:hover {
    background-color: #e0a800;
  }
</style>

<h2>Add New Movie</h2>

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name"><br>
  <input type="text" name="desc" placeholder="Enter the movie description"><br>
  <input type="text" name="year" placeholder="Enter the movie year"><br>
  <input type="file" name="img"><br>
  <input type="submit"><br>
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

<style>
    .navbar.navbar-dark {
        background-color: rgba(50, 50, 50, 0.8);
        box-shadow: 0px 10px 30px rgba(0, 0, 0, 1);
    }

    .navbar.navbar-dark .navbar-brand {
        color: white;
        font-size: 33px; /* Increased font size */
        font-weight: bold;
    }

    .navbar.navbar-dark .navbar-nav .nav-link,
    .navbar.navbar-dark .home-link,
    .navbar.navbar-dark .add-movie-link {
        color: #FFD700; /* Yellow font color */
        font-size: 18px;
        font-weight: 500;
        padding: 15px 10px;
        text-transform: uppercase; /* Uppercase text */
    }

    .navbar.navbar-dark .navbar-nav .nav-link:hover,
    .navbar.navbar-dark .home-link:hover,
    .navbar.navbar-dark .add-movie-link:hover,
    .navbar.navbar-dark .navbar-toggler-icon:hover {
        color: #FFD700; /* Hover color */
    }

    .navbar.navbar-dark .navbar-toggler-icon {
        background-color: white;
    }

    .navbar.navbar-dark .home-link {
        margin-left: auto; /* Right align */
    }
</style>


</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark" id="navbar_sticky">
        <a class="navbar-brand" href="{% url 'movieapp:index' %}">
            CineLane
        </a>
        <ul class="navbar-nav ml-auto">
            <!-- Home link -->
            <li class="nav-item">
                <a class="nav-link home-link" href="{% url 'movieapp:index' %}">
                    Home
                </a>
            </li>
            <!-- Add New Movie link -->
            <li class="nav-item">
                <a class="nav-link add-movie-link" href="{% url 'movieapp:add_movie' %}">
                    Add New Movie
                </a>
            </li>
        </ul>
    </nav>
    {% block body %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-U1sMWEgq4BpIxxGnRXPqzqoPqe92L2JpPA+DfLX8jskKOqjAzmhAUV6UbbBGFmck"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous"></script>
</body>

</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<style>
  body {
    background-color: #1c1c1c;
    color: #fff;
    margin: 0;
    font-family: 'Arial', sans-serif;
  }

  .container {
    text-align: center;
    padding: 50px 0;
  }

  .col-md-6 {
    background-color: #333;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  }

  form {
    margin-top: 20px;
  }

  p.text-center {
    font-size: 1.5rem;
    margin-bottom: 30px;
  }

  .btn-danger {
    background-color: #dc3545;
    border-color: #dc3545;
    padding: 10px 20px;
    font-size: 1rem;
    border-radius: 5px;
  }

  .btn-danger:hover {
    background-color: #c82333;
    border-color: #c82333;
  }
</style>

<div class="container my-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}

                <p class="text-center text-white">Are you sure you want to delete this movie?</p>

                <div class="text-center">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<style>
  body {
    background-color: #1c1c1c;
    color: #fff;
    margin: 0;
  }

  .container {
    padding-top: 50px;
  }

  .col-md-6 {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-bottom: 10px; /* Reduce the margin between columns */
  }


  img {
    max-width: 100%;
    max-height: 70vh;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    margin-right: 10px; /* Adjust the margin to the right of the image */
  }

  .col-md-6.movie-info {
    text-align: left;
    margin-left: 10px; /* Adjust the left margin of the movie info column */
    margin-right: 0; /* Remove or adjust the right margin of the movie info column */
  }

  .col-md-4.image-card {
      max-width: 60%; /* Set maximum width to 100% */
      margin-right: 20px;
      border: none;
      background-color: transparent;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
      border-radius: 8px;
      overflow: hidden;
      text-align: left;
  }

  h1 {
    font-size: 2.5rem;
    margin-bottom: 10px;
  }

  h5 {
    font-size: 1.2rem;
    color: #ffc107; /* Change year color to yellow */
    margin-bottom: 20px;
  }

  p {
    font-size: 1.2rem;
    line-height: 1.6;
  }

  .btn {
    margin-top: 15px;
  }

  .btn-warning,
  .btn-danger {
    background-color: #ffc107; /* Change button background color to yellow */
    border-color: #ffc107; /* Change button border color to yellow */
    color: #1c1c1c; /* Change button text color to black */
    border-radius: 8px; /* Add border-radius for rounded corners */
    transition: background-color 0.3s, border-color 0.3s, color 0.3s, box-shadow 0.3s;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2); /* Add box shadow for a subtle lift */
    font-weight: bold; /* Make button text bold */
    font-size: 1.2rem; /* Increase button text size */
  }

  .btn-warning:hover,
  .btn-danger:hover {
    background-color: #e0a800; /* Darken button background color on hover */
    border-color: #e0a800; /* Darken button border color on hover */
    color: #1c1c1c; /* Change text color on hover */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Increase box shadow on hover */
  }

  .btn-danger {
    margin-right: 10px; /* Add margin-right for spacing between buttons */
  }
</style>

<div class="container my-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.img.url }}" class="img-fluid" alt="{{ movie.name }}">
        </div>

        <div class="col-md-6">
            <div class="text-light">
                <h1>{{ movie.name }}</h1>
                <span><h5>{{ movie.year }}</h5></span>
                <p>{{ movie.desc }}</p>

                <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>

                <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<style>
  body {
    background-color: #1c1c1c;
    color: #fff;
    margin: 0;
    font-family: 'Arial', sans-serif;
  }

  .container {
    padding: 40px 0; /* Reduced padding for the container */
    max-width: 1000px;
    margin: 0 auto;
  }

  h2 {
    color: #ffc107;
    text-align: center;
    margin-bottom: 20px; /* Reduced margin-bottom for the heading */
    font-weight: bold; /* Added font-weight: bold; for the heading */
  }

  form {
    padding: 20px;
    margin: 20px auto;
    max-width: 800px;
    background-color: #333;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
  }

  .btn-primary {
    background-color: #ffc107;
    border-color: #ffc107;
    padding: 10px 20px;
    font-size: 1rem;
    border-radius: 5px;
    color: #000000;
  }

  .btn-primary:hover {
    background-color: #e0a800;
    border-color: #e0a800;
  }

  .form-group {
    margin-bottom: 20px;
  }

  label {
    font-weight: bold;
    color: #fff;
    display: block;
    margin-bottom: 8px;
  }

  .required {
    color: #dc3545;
    margin-left: 5px;
  }

  input[type="text"],
  input[type="file"] {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #444;
    border-radius: 5px;
    margin-bottom: 10px;
    color: #333;
  }

  textarea {
    width: calc(100% - 22px);
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #444;
    border-radius: 5px;
    margin-bottom: 10px;
    color: #333;
    resize: vertical;
    height: 80px;
  }
</style>

<div class="container my-4">
    <h2 class="text-center mb-4">Update Movie</h2>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Movie Name<span class="required">*</span>:</label>
                    {{ form.name }}
                </div>

                <div class="form-group">
                    <label for="id_desc">Movie Description<span class="required">*</span>:</label>
                    {{ form.desc }}
                </div>

                <div class="form-group">
                    <label for="id_year">Movie Year<span class="required">*</span>:</label>
                    {{ form.year }}
                </div>

                <div class="form-group">
                    <label for="id_img">Movie Image<span class="required">*</span>:</label>
                    {{ form.img }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}
<style>
    body {
        background-color: #000;
        color: #fff;
        margin: 0;
    }

    .container {
        text-align: center;
        padding: 20px 10px;
        width: 100%;
        max-width: 1400px;
        height: 100vh;
        box-sizing: border-box;
    }

    .row {
        display: flex;
        justify-content: center;
        gap: 30px;
        flex-wrap: wrap;
    }

    .col-md-3 {
        flex: 0 0 22%;
        max-width: 22%;
        margin-bottom: 30px;
    }

    .movie-card {
        border-radius: 10px;
        overflow: hidden;
        transition: transform 0.2s, box-shadow 0.2s;
        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
        background-color: #111;
        border: none;
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
    }

    .card-img-top {
        object-fit: cover;
        height: 60%;
        width: 100%;
    }

    .card-body {
        padding: 20px;
        text-align: left;
        flex-grow: 1;
    }

    .card-title {
        font-size: 1.6rem;
        margin-bottom: 12px;
    }

    .card-text {
        color: #ddd;
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 3;
        -webkit-box-orient: vertical;
        font-size: 1rem;
    }

    .btn-details {
        background-color: #ffc107;
        border-color: #ffc107;
        color: #000000;
        outline: none; /* Remove outline on focus */
    }

    .btn-details:hover,
    .btn-details:active {
        background-color: #e0a800;
        border-color: #e0a800;
    }
</style>

<div class="container my-4">
    <div class="row">
        {% for movie in movie_list %}
        <div class="col-md-3">
            <div class="card movie-card">
                <img class="card-img-top" src="{{ movie.img.url }}" alt="{{ movie.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ movie.name }}</h5>
                    <p class="card-text">{{ movie.desc }}</p>
                    <a href="{% url 'movieapp:detail' movie.id %}" class="btn btn-details">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}